USER_LIB_PATH = /home/glyn/Arduino/libraries
AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf


ARDUINO_LIBS = jeelib OneWire VirtualWire  DallasTemperature
BOARD_TAG    = atmega328

include /home/glyn/Downloads/tools/Arduino-Makefile/Arduino.mk


